# Generated by Django 5.2.14 on 2026-07-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('📁', 'Folder'), ('📋', 'Clipboard'), ('🎯', 'Target'), ('💡', 'Idea'), ('🏠', 'Home'), ('💼', 'Work'), ('📚', 'Study'), ('✨', 'Spark'), ('🌱', 'Growth'), ('⚡', 'Energy')], default='📋', max_length=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('priority', models.CharField(choices=[('U', 'Urgent'), ('I', 'Important'), ('IU', 'Important and urgent'), ('C', 'Casual')], default='C', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], default='P', max_length=1)),
            ],
            options={
                'ordering': ['expiration_date'],
            },
        ),
    ]
